### PR TITLE
fixed brightness and added all rainbow colors

### LINKED ISSUE #3: The Swatch of colors to choose from should be brighter and have all the colors of the rainbow
Color Swatch has a reflection and faded color since the change in SDK it seems.  Need the colors in the swatch to be bright like in the initial readme picture.

### PR DESCRIPTION
**Pull request by mul1sh**
fixes #3

### CODE REVIEW

**Review by skr-v — CHANGES_REQUESTED** [review]
> Processing /src/modules/pixels.ts
  Error /src/modules/pixels.ts (107,30): Property 'alpha' does not exist on type 'Material'.
  Error /src/modules/pixels.ts (108,1): Type 'Color4' is missing the following properties from type 'Color3': toColor4, toLuminance, equals, equalsFloats, and 2 more.
  Error /src/modules/pixels.ts (110,1): Type 'Color4' is not assignable to type 'Color3'.
  Error /src/modules/pixels.ts (111,30): Property 'hasAlpha' does not exist on type 'Material'.
> Emitting /bin/game.js

Hi Mul1sh,  I get these errors when running now.

**Comment by mul1sh** [comment]
@skr-v i think you maybe running an old version of decentraland, trying running `npm install decentraland-ecs@latest -g` to update it and then run it again.

**Review by skr-v — CHANGES_REQUESTED** [review]
The colors are still faded when I test it how the devs recommend right now.

**Comment by mul1sh** [comment]
Ok so how are you testing now @skr-v?

**Comment by skr-v** [comment]
On 6.4.5... does it run for you? Not for me as 6.4.5 has the issue at the
moment.


On Friday, February 28, 2020, Mulili Nzuki <notifications@github.com> wrote:
> Ok so how are you testing now @skr-v?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/VW7-dNGFHHnZUSRMKPTgqAOemssXbloZUqB9W4tC1B5vrtN0GEmrzhvPKFVwyBnM6UKWWBgcM6XCvXJWHPqlcM85kkaxyYot24LWKhuTFmlyLdlVmIqcG182LknBeJu9dK2rqGEQmfcZa-fyyAYQwE44YOsdSjHSRjJv2Vt7JgqrgvvFqFPIy05LuL7-jy8w4lb4Awbwh67N-YQ77v4viPCFMgHRdPo_gS3ime2HAA=s0-d-e1-ft#https://github.com/notifications/beacon/ABNAZIYLLYXXPCNZBGS3YPTRFBZEXA5CNFSM4K4DWMU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENGXTKQ.gif>

**Comment by mul1sh** [comment]
Ok thanks, looking into this again

**Comment by mul1sh** [comment]
@skr-v this should be working as required now, kindly check

**Comment by skr-v** [comment]
pixels
This is what I see when running now, are you seeing this?
I tried many times with SDK version 6.4.4, 6.4.5 and 6.4.7 and even on 6.4.4 which used to run fine now the swatch colors turn brown after clicking, so new issues popping up, also not sure why you are doing deletions of the import statements, it makes testing and integrating more difficult

**Comment by mul1sh** [comment]
@skr-v  yes thats what i'm also seeing, i turned up the emissionIntensity to make color's more brighter. No sure about the swatch colors turning brown, will have to look into that more closely.

I deleted the import statements because they are actually not being used, but I could re-add them if you want me to, no worries. Let me also look into the swatch colors too.

**Comment by skr-v** [comment]
Yea those deletions may be why I'm getting the swatch turning brown.  It
doesn't happen on the older versions

**Comment by mul1sh** [comment]
ok i've restored the imports, but i'm still not getting the swatch to turn brown on my end. I would suggest  maybe try deleting the `bin`  folder and then run `npm start` again to clear out any cached code.

**Comment by skr-v** [comment]
If it looked like the screenshot from the readme then this would be fixed, but it looks too reflective still.

**Comment by mul1sh** [comment]
ok, let me try some more modifications then

**Comment by mul1sh** [comment]
@skr-v  I've updated it, turns out its the newer versions of decentraland-ecs sdk that were causing it to dim. So switching to the older versions will sort this bug. Don't forget to reinstall your `node_modules` too and run when testing.

If it hangs when loading, please refresh and it will work, there is a bug in the latest `dcl` that makes it hang but on refresh all is sorted.

Please checkout this screenshot for comparison
Screenshot 2020-03-10 at 10 32 20 PM

**Comment by skr-v** [comment]
Switching to the older version of the SDK is not possible in production so
a downgrade is not a solution.  I know this is a tricky problem since the
start.  This issue should not even be happening at all, or it should be
possible to easily change the reflectivity levels.   I will close this in
your favour for the time you have spent, thank you, and good luck in the
future.

**Comment by skr-v** [comment]
Just post a PR for your latest swatches colour selector Hex code update and
I will payout the bounty, thanks

**Comment by mul1sh** [comment]
@skr-v  Thanks for the feedback and sorry for this, I wish there was something I could do but since its caused by SDK updates and its also not possible to change the reflectivity levels of a pixel based on the [official docs](https://github.com/decentraland/ecs-reference/blob/master/docs-6.0/decentraland-ecs.material.md) their is only so much I could do.

I have updated the PR to only have the swatches colour selector Hex code update and a README fix, everything else stays the same. Thank you.

**Comment by mul1sh** [comment]
I updated the swatches @skr-v, any more changes you want me to make?

**Comment by skr-v** [comment]
Please create a new pull request from master with only the color swatch hex
code updates, there have been some changes to other files that I prefer to
not touch, please in the future do not change code that is not part of your
solution, it looks suspicious and takes longer to review. Submit that new
PR to gitcoin and I will approve it for you.  Thanks

**Comment by mul1sh** [comment]
OK understood, doing so now.

**Comment by moonsuyoung** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sfss5362, @hjh010501, @allenleexyz, @ucsusse, @msalade, @BananaGikoH, @yureribeiro, @Zihin, @validvoid, @khoerling, @833Y, @alexanderdoty, @brandon-o, @CuthbertJungle, @leandroo, @zamazan4ik, @j3ers3, @ionescu77, @tiankonguse, @jchatard, @stevexyh, @alpinemoose, @ssured, @bittergrass, @leochen2038, @veloute, @cnhua, @kirtangajjar, @JimmyRowland, @oblique, @lepiaf, @triple-j, @bjsunhe, @zicklag, @Quotz, @brooklet, @alxbob, @ikkira, @Misaka13514, @edtechdev, @tylerxue, @yyuueexxiinngg, @chqingdev, @avelardi, @jackxu8, @kn0rhaan, @sssaini, @sudokai, @blue-bird1, @ponycoolicyfish, @Swenyx, @CPCer, @suikodev, @secretgspot, @afonsopacifer, @swiftcore, @ethfun, @huoniu, @skymagician, @GuaiLong618, @cuzzo, @liaoyijun, @WangXiZhu, @adambillcooper, @amiracle, @YunQimg, @pheuter, @anotherglitchinthematrix, @cantalupo555, @bojidar-bg, @wotwot563, @anC8899, @hiorws, @Exely, @luizbaldi, @ibakirov, @getuniv, @myfreeer, @MirceaKitsune, @BENMFeng, @swapnil0545, @ccdle12, @rafacv, @xcm153, @CoreJK, @laizy, @jasl, @dondreytaylor, @hectorabyx, @Astraeux, @lcmftianci, @Ignatius-OTC, @nullpunkt5, @haroldduan, @yechs, @bradvo, @xiaojay, @zhangakui002, @nanpanman

**Pull request closed without merging**
